services:
  k8sd:
    override: replace
    command: bash -c "$SNAP/k8s/wrappers/services/k8sd"
    startup: enabled

  containerd:
    override: replace
    command: bash -c "$SNAP/k8s/wrappers/services/containerd"
    startup: disabled
    before: [kubelet]

  k8s-dqlite:
    override: replace
    command: bash -c "$SNAP/k8s/wrappers/services/k8s-dqlite"
    startup: disabled
    before: [kube-apiserver]

  kube-apiserver:
    override: replace
    command: bash -c "$SNAP/k8s/wrappers/services/kube-apiserver"
    startup: disabled
    before: [kubelet, kube-controller-manager, kube-proxy, kube-scheduler]

  kubelet:
    override: replace
    command: bash -c "$SNAP/k8s/wrappers/services/kubelet"
    startup: disabled
    after: [containerd]

  kube-controller-manager:
    override: replace
    command: bash -c "$SNAP/k8s/wrappers/services/kube-controller-manager"
    startup: disabled
    after: [kube-apiserver]

  kube-scheduler:
    override: replace
    command: bash -c "$SNAP/k8s/wrappers/services/kube-scheduler"
    startup: disabled
    after: [kube-apiserver]

  kube-proxy:
    override: replace
    command: bash -c "$SNAP/k8s/wrappers/services/kube-proxy"
    startup: disabled
    after: [kube-apiserver]

  k8s-apiserver-proxy:
    override: replace
    command: bash -c "$SNAP/k8s/wrappers/services/k8s-apiserver-proxy"
    startup: disabled
    before: [kube-proxy, kubelet]
