network:
  release: "ck-network"
  chart: "cilium-1.14.1.tgz"
  namespace: "kube-system"
dns:
  release: "ck-dns"
  chart: "coredns-1.29.0"
  namespace: "kube-system"
storage:
  release: "ck-storage"
  chart: "rawfile-csi-0.8.0.tgz"
  namespace: "kube-system"
ingress:
  parent: "network"
gateway:
  release: "ck-gateway"
  chart: "gateway-api-0.7.1.tgz"
  namespace: "kube-system"
loadbalancer:
  release: "ck-loadbalancer"
  chart: "ck-loadbalancer"
  namespace: "kube-system"
