name: Backport merged pull request
on:
  pull_request_target:
    types: [closed]
  issue_comment:
    types: [created]

permissions:
  contents: read

jobs:
  backport:
    name: Backport pull request
    runs-on: ubuntu-latest
    permissions:
      # contents: write is required by the backport action to create and push backport branches
      contents: write
      pull-requests: write # so it can create pull requests

    # Only run when pull request is merged
    # or when a comment containing `/backport` is created by someone other than the
    # https://github.com/backport-action bot user (user id: 97796249). Note that if you use your
    # own PAT as `github_token`, that you should replace this id with yours.
    # cdkbot's user ID is 99445902.
    if: >
      (
        github.event_name == 'pull_request_target' &&
        github.event.pull_request.merged
      ) || (
        github.event_name == 'issue_comment' &&
        github.event.issue.pull_request &&
        github.event.comment.user.id != 99445902 &&
        contains(github.event.comment.body, '/backport')
      )
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create backport pull requests
        id: create_backports
        # v3.2.0
        uses: korthout/backport-action@436145e922f9561fc5ea157ff406f21af2d6b363
        with:
          # Set (default) action parameters explicitly.
          branch_name: backport-${pull_number}-to-${target_branch}
          cherry_picking: auto
          copy_assignees: false
          copy_milestone: false
          copy_requested_reviewers: false
          experimental: >
            {
              "conflict_resolution": "fail"
            }
          github_token: ${{ secrets.BOT_TOKEN }}
          github_workspace: ${{ github.workspace }}
          label_pattern: ^backport ([^ ]+)$
          merge_commits: fail
          pull_description: |-
            # Description
            Backport of #${pull_number} to `${target_branch}`.
          pull_title: >-
            ${pull_title} [Backport ${target_branch}]

      - name: Label backports with automerge and approve
        env:
          GH_TOKEN: ${{ secrets.BACKPORT_APPROVAL_TOKEN }}
        run: |
          for pr_number in ${{ steps.create_backports.outputs.created_pull_numbers }}; do
            gh pr edit "$pr_number" --add-label "automerge"
            gh pr review "$pr_number" --approve
          done
