name: Documentation Spelling Check

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'docs/**'
permissions:
  contents: read

jobs:
  doc-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install vale
        run: sudo snap install vale
      - id: spell-check
        name: Spell Check
        run: vale --glob='*.{md,txt,rst}' .
        working-directory: docs/canonicalk8s

      - name: Link Check
        id: linkcheck-step
        if: success() || failure()
        uses: canonical/documentation-workflows/linkcheck@main
        with:
          working-directory: docs/canonicalk8s

      #  continue-on-error: true
      # - if: ${{ github.event_name == 'pull_request' && steps.spell-check.outcome == 'failure' }}
        # uses: actions/github-script@v6
        # with:
        #   script: |
        #     github.rest.issues.createComment({
        #       issue_number: context.issue.number,
        #       owner: context.repo.owner,
        #       repo: context.repo.repo,
        #       body: 'Hi, looks like the vale spelling job found some issues, you can check it [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})'
        #     })
