name: Go

on:
  push:
    branches:
      - main
      - autoupdate/strict
      - 'release-[0-9]+.[0-9]+'
      - 'autoupdate/release-[0-9]+.[0-9]+-strict'
  pull_request:

permissions:
  contents: read  

jobs:
  test:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: write  # for marocchino/sticky-pull-request-comment to create or update PR comment
    name: Unit Tests & Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: go mod download
        working-directory: src/k8s
        run: go mod download

      - name: go fmt
        working-directory: src/k8s
        run: make go.fmt

      - name: go doc
        working-directory: src/k8s
        run: make go.doc

      - name: check diff
        run: |
          if ! [ -z "$(git diff)" ]; then
            echo "Detected changes that have not been committed to the repository"
            echo "Please run 'cd src/k8s && make go.fmt go.doc'"
            echo "git diff:"
            git diff
            exit 1
          fi

      - name: go vet
        working-directory: src/k8s
        run: make go.vet

      - name: go deadcode
        working-directory: src/k8s
        run: make go.deadcode

      - name: go test
        working-directory: src/k8s
        run: |
          make go.unit
          go install github.com/boumenot/gocover-cobertura@latest
          gocover-cobertura < coverage.txt > coverage.xml

      - name: Generate code coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: src/k8s/coverage.xml
          badge: false
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: false
          output: both
          thresholds: '60 80'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
        continue-on-error: true

  test-binary:
    name: Binaries
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: go mod download
        working-directory: src/k8s
        run: go mod download

      - name: Build static binaries
        working-directory: src/k8s
        run: |
          make -j static

          ./bin/static/k8s --help
          ./bin/static/k8sd --help
          ./bin/static/k8s-apiserver-proxy --help

      - name: Build shared binaries
        working-directory: src/k8s
        run: |
          make -j dynamic
          export LD_LIBRARY_PATH=bin/dynamic/lib

          ./bin/dynamic/k8s --help
          ./bin/dynamic/k8sd --help
          ./bin/dynamic/k8s-apiserver-proxy --help
