name: Linkcheck 

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      branch: 
        description: 'Branch to run the tests on'
        type: string
        required: false
      changed_files:
        type: string
        default: '.'

jobs:
  linkcheck: 
    name: Run linkchecker 
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch || github.event.pull_request.head.sha }}
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Run linkcheck 
        run: |
          echo "Changed files: ${{ inputs.changed_files }}"
          python3 docs/canonicalk8s/.sphinx/linkcheck.py docs/canonicalk8s \
          --install_target install \
          --linkcheck_target linkcheck \
          --makefile Makefile \
          "${{ inputs.changed_files }}"
        shell: bash  
