name: Linkcheck 

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      ref: 
        description: 'Branch to run the tests on'
        type: string
        required: false
      repo:
        description: 'Repo to run the tests on'
        type: string
        required: false
        default: ${{ github.repository }}
      changed_files:
        type: string
        default: ''

jobs:
  prepare:
    name: Prepare Environment
    runs-on: ubuntu-latest
    outputs:
      repo: ${{ steps.compute-ref.outputs.repo }}
      ref: ${{ steps.compute-ref.outputs.ref }}
    steps:
      - name: Compute ref for test collection
        id: compute-ref
        shell: bash
        run: |
          # Determine from which rev to collect the tests, resolved in order:
          # 1. inputs.ref if set
          # 2. main branch

          REF="main"
          
          if [ -n "${{ inputs.ref }}" ]; then
            REF="${{ inputs.ref }}"
          fi

          echo "Using git ref $REF"
          echo "repo=${{ inputs.repo }}" >> $GITHUB_OUTPUT
          echo "ref=$REF" >> $GITHUB_OUTPUT
  linkcheck: 
    name: Run linkchecker 
    runs-on: ubuntu-latest 
    needs: prepare
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: ${{ needs.prepare.outputs.repo }}
          ref: ${{ needs.prepare.outputs.ref }}
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Run linkcheck 
        run: |
          CHANGED_FILES="${{ inputs.changed_files }}"
          echo "Running linkcheck with files: $CHANGED_FILES"

          # echo "Changed files: ${{ inputs.changed_files }}"
          python3 docs/canonicalk8s/.sphinx/linkcheck.py docs/canonicalk8s \
            --install_target install \
            --linkcheck_target linkcheck \
            --makefile Makefile \
            "$CHANGED_FILES"
        shell: bash  
