name: TICS Analysis

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  TICS:
    runs-on: [self-hosted, linux, amd64, tiobe, jammy]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python venv and install dependencies
        run: |
          set -ex
          sudo apt-get update
          sudo apt-get install -y python3-venv
          python3 -m venv .venv/tics
          source .venv/tics/bin/activate
          pip install -r tests/integration/requirements-test.txt
          pip install -r tests/integration/requirements-dev.txt

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: src/k8s/go.mod

      - name: Prepare Go coverage and build
        run: |
          set -ex
          sudo env "PATH=$PATH" make go.unit
          go install github.com/boumenot/gocover-cobertura@latest
          gocover-cobertura <coverage.txt >cobertura.xml
          mkdir -p .coverage
          mv ./cobertura.xml .coverage/
          go install honnef.co/go/tools/cmd/staticcheck@v0.5.1
        working-directory: src/k8s

      - name: Install dqlite dependencies
        run: |
          set -ex
          release="$(lsb_release --codename --short)"
          wget -qO- "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x392A47B5A84EACA9B2C43CDA06CD096F50FB3D04" | sudo tee /etc/apt/trusted.gpg.d/dqlite-dev.asc
          echo "deb-src https://ppa.launchpadcontent.net/dqlite/dev/ubuntu $release main" | sudo tee /etc/apt/sources.list.d/dqlite-dev.list
          echo "deb https://ppa.launchpadcontent.net/dqlite/dev/ubuntu $release main" | sudo tee /etc/apt/sources.list.d/dqlite-dev.list
          sudo apt-get update
          sudo apt-get install -y dqlite-tools-v2 libdqlite1.17-dev
          sudo make clean
          go build -a ./...
        working-directory: src/k8s

      - name: Run TICS
        uses: tiobe/tics-github-action@v3
        with:
          mode: qserver
          project: k8s-snap
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=GoProjects
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true
