name: Check for component upgrades

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"
  pull_request:
    paths:
      - .github/workflows/update-components.yaml

permissions:
  contents: read

jobs:
  update:
    permissions:
      contents: write # for peter-evans/create-pull-request to create branch
      pull-requests: write # for peter-evans/create-pull-request to create a PR
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch:
          # Keep main branch up to date
          - main
          # Supported release branches
          - release-1.34
          - release-1.33
          - release-1.32

    steps:
      - name: Checking out repo
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
          ssh-key: ${{ secrets.BOT_SSH_KEY }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip3 install -r ./build-scripts/hack/requirements.txt

      - name: Check for new component versions
        run: |
          ./build-scripts/hack/update-component-versions.py

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "[${{ matrix.branch }}] Update component versions"
          title: "[${{ matrix.branch }}] Update component versions"
          body: "[${{ matrix.branch }}] Update component versions"
          branch: "autoupdate/sync/${{ matrix.branch }}"
          labels: |
            automerge
          delete-branch: true
          base: ${{ matrix.branch }}
          token: ${{ secrets.BOT_TOKEN }}
          author: "K8s builder bot <k8s-bot@canonical.com>"
