name: Check for k8sd Go dependency updates

on:
  workflow_dispatch:
  schedule:
    - cron: "0 11 * * *"
  pull_request:
    paths:
      - .github/workflows/update-k8sd-go-deps.yaml

permissions:
  contents: read

jobs:
  update:
    permissions:
      contents: write # for peter-evans/create-pull-request to create branch
      pull-requests: write # for peter-evans/create-pull-request to create a PR
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch:
          # Keep main branch up to date
          - main
          # Supported release branches
          - release-1.35
          - release-1.34
          - release-1.33
          - release-1.32

    steps:
      - name: Checking out repo
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
          ssh-key: ${{ secrets.BOT_SSH_KEY }}

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './src/k8s/go.mod'

      - name: Update k8sd Go dependencies
        run: |
          if [ "${{ matrix.branch }}" = "main" ]; then
            UPDATE_FLAG="-u"
          else
            UPDATE_FLAG="-u=patch"
          fi
          
          cd src/k8s
          go get $UPDATE_FLAG ./...
          go mod tidy
          
          cd $GITHUB_WORKSPACE/src/k8s/tools
          go get $UPDATE_FLAG ./...
          go mod tidy

      - name: Create pull request
        if: github.event_name != 'pull_request'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "[${{ matrix.branch }}] Update k8sd Go dependencies"
          title: "[${{ matrix.branch }}] Update k8sd Go dependencies"
          body: "[${{ matrix.branch }}] Update k8sd Go dependencies"
          branch: "autoupdate/k8sd-go-deps/${{ matrix.branch }}"
          labels: |
            automerge
          delete-branch: true
          base: ${{ matrix.branch }}
          token: ${{ secrets.BOT_TOKEN }}
          author: "K8s builder bot <k8s-bot@canonical.com>"
